name: SFDX-CI (Org-based dev)
on:
  pull_request:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3

      # Run PMD Scan
      - name: "Run PMD Scan"
        uses: pmd/pmd-github-action@v1
        id: pmd
        with:
          sourcePath: "force-app"
          rulesets: "ruleset.xml"

      - name: "Install SFDX CLI and Authenticate to a dev org"
        uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: "Install SFDX Delta creator node app"
        run: |
          sudo npm install sfdx-git-delta@latest -g
          git config remote.config.fetch '+refs/heads/*:refs/remotes/origin/*'
          git fetch --all
          git checkout -b pr
          git --no-pager diff --name-status pr origin/staging
          sgd --to pr --from origin/staging --repo . --output .
          cat package/package.xml
      - name: "Convert metadata"
        run: "sfdx force:source:convert --manifest=package/package.xml --outputdir=convert"
      - name: "Run LocalTests"
        run: "sfdx force:mdapi:deploy --deploydir=convert --testlevel=RunLocalTests --checkonly -w30"
