name: SFDX-CI (Org-based dev)
on: 
  push: 
    branches: [ staging ]

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: sfdx-actions/setup-sfdx@v1
        with: 
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: "Install SFDX Delta creator node app"
        run: |
        sudo npm install sfdx-git-delta@latest -g
        git config remote.config.fetch '+refs/heads/*:refs/remotes/origin/*'
        git fetch --all
        git --no-pager diff --name-status staging origin/main
        sgd --to staging --from origin/main --repo . --output .
        cat package/package.xml
      - name: 'Convert metadata'
        run: 'sfdx force:source:convert --manifest=package/package.xml --outputdir=convert'
      - name: 'Deploy to org'
        run: 'sfdx force:mdapi:deploy --deploydir=convert -w30'
